# Generated by Django 5.2.3 on 2025-12-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullloads', '0006_booking_booking_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'ordering': ['weight']},
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='weight',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
