# Generated by Django 5.2.3 on 2026-01-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullloads', '0007_alter_vehicletype_options_vehicletype_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.CharField(max_length=255)),
                ('surge_increase', models.IntegerField(blank=True)),
                ('surge_decrease', models.IntegerField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
