# Generated by Django 5.2.3 on 2026-01-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullloads', '0008_surge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surge',
            old_name='surge_decrease',
            new_name='surge_decrease_percent',
        ),
        migrations.RenameField(
            model_name='surge',
            old_name='surge_increase',
            new_name='surge_increase_percent',
        ),
    ]
