# Generated by Django 5.2.3 on 2026-01-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullloads', '0009_rename_surge_decrease_surge_surge_decrease_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surge',
            name='surge_decrease_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surge',
            name='surge_increase_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
