# Generated by Django 5.2.3 on 2026-01-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullloads', '0010_alter_surge_surge_decrease_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surge',
            name='weight_tiers',
            field=models.ManyToManyField(blank=True, related_name='fullload_surges', to='fullloads.weighttier'),
        ),
    ]
