# Generated by Django 5.2.3 on 2026-01-29 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullloads', '0011_surge_weight_tiers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surge',
            name='weight_tiers',
        ),
        migrations.AddField(
            model_name='surge',
            name='weight_tiers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fullload_surges', to='fullloads.weighttier'),
        ),
    ]
