# Generated by Django 5.2.3 on 2026-02-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullloads', '0012_remove_surge_weight_tiers_surge_weight_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='recipient_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='recipient_phone',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
