# Generated by Django 5.2.3 on 2025-12-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_office_intracity_radius_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='pickup_first_free_kms',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
