# Generated by Django 5.2.3 on 2026-04-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0048_remove_intracitypackagepricing_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'mpesa'), ('cash', 'cash'), ('card', 'card')], default='mpesa', max_length=50),
        ),
    ]
