# Generated by Django 5.2.3 on 2025-12-16 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0003_internationalorders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
    ]
