# Generated by Django 5.2.3 on 2025-12-16 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0004_alter_country_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
    ]
