# Generated by Django 5.2.3 on 2025-12-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0005_alter_city_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalpolicy',
            name='is_direct_price',
            field=models.BooleanField(default=False),
        ),
    ]
