# Generated by Django 5.2.3 on 2025-12-16 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0006_internationalpolicy_is_direct_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internationalpolicy',
            old_name='is_direct_price',
            new_name='is_flat_price',
        ),
    ]
