# Generated by Django 5.2.3 on 2025-12-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0007_rename_is_direct_price_internationalpolicy_is_flat_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internationalorders',
            old_name='recipient_city',
            new_name='city',
        ),
        migrations.AddField(
            model_name='internationalorders',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalorders',
            name='is_fragile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internationalorders',
            name='mpesaphone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='internationalorders',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
