# Generated by Django 5.2.3 on 2025-12-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0008_rename_recipient_city_internationalorders_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalorders',
            name='sender_name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
