# Generated by Django 5.2.3 on 2026-02-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0009_internationalorders_sender_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalorders',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
